#!/bin/bash
# merge.sh -- Merge Playwright recording + subtitles + 8-bit audio -> final demo.mp4
#
# Supports 3 tiers of audio complexity:
#   1. Video + subtitles only (--no-bgm)
#   2. Video + subtitles + BGM
#   3. Video + subtitles + BGM + narration clips (from audio/*.mp3)
#
# Prerequisites:
#   - ffmpeg installed
#   - Playwright recording completed (recordings/*.webm)
#   - subtitles.srt generated by playwright-record.ts
#   - (Optional) bgm.mp3 -- 8-bit chiptune background music
#   - (Optional) audio/narration-*.mp3 -- TTS narration clips
#   - (Optional) narration.json -- timing data from playwright-record.ts
#
# Usage:
#   ./merge.sh                   # full merge (video + srt + bgm + narration)
#   ./merge.sh --no-bgm          # video + subtitles only (silent)
#   ./merge.sh --bgm-only        # video + srt + bgm (skip narration)
#   ./merge.sh --dry-run          # print ffmpeg command without running
#   ./merge.sh --no-subs          # skip subtitle burn-in
#   ./merge.sh --output out.mp4   # custom output path

set -euo pipefail

DEMO_DIR="$(cd "$(dirname "$0")" && pwd)"
VIDEO_DIR="$DEMO_DIR/recordings"
SRT_FILE="$DEMO_DIR/subtitles.srt"
BGM_FILE="$DEMO_DIR/bgm.mp3"
NARRATION_DIR="$DEMO_DIR/audio"
NARRATION_JSON="$DEMO_DIR/narration.json"
OUTPUT="$DEMO_DIR/demo.mp4"

# Flags
NO_BGM=false
BGM_ONLY=false
DRY_RUN=false
NO_SUBS=false

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-bgm)   NO_BGM=true; shift ;;
    --bgm-only) BGM_ONLY=true; shift ;;
    --dry-run)  DRY_RUN=true; shift ;;
    --no-subs)  NO_SUBS=true; shift ;;
    --output)   OUTPUT="$2"; shift 2 ;;
    *)          echo "Unknown arg: $1"; exit 1 ;;
  esac
done

echo "========================================"
echo " Hermes Quest Demo -- Post-Production"
echo "========================================"

# --- 1. Find the recorded video ---
VIDEO=$(ls -t "$VIDEO_DIR"/*.webm 2>/dev/null | head -1)
if [ -z "$VIDEO" ]; then
  echo "ERROR: No .webm video found in $VIDEO_DIR/"
  echo "Run the Playwright recording first: npx tsx playwright-record.ts"
  exit 1
fi
echo "Video:      $VIDEO"
echo "Output:     $OUTPUT"

# --- 2. Check subtitle file ---
if [ ! -f "$SRT_FILE" ]; then
  echo "WARN: Subtitle file not found: $SRT_FILE"
  NO_SUBS=true
fi
[ "$NO_SUBS" = false ] && echo "Subtitles:  $SRT_FILE"

# --- 3. Subtitle style (pixel-art warm gold) ---
# Press Start 2P font, warm gold text, dark brown outline
SUB_STYLE="FontName=Press Start 2P,FontSize=14,PrimaryColour=&H0068e6f0,OutlineColour=&H00140a0a,BorderStyle=3,Outline=2,Shadow=1,MarginV=30"

# Escape SRT path for ffmpeg subtitles filter
SRT_ESCAPED=$(echo "$SRT_FILE" | sed "s/'/\\\\'/g" | sed 's/:/\\:/g')

# --- 4. Get video duration ---
VIDEO_DURATION=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$VIDEO" 2>/dev/null || echo "300")
echo "Duration:   ${VIDEO_DURATION}s"

# --- 5. Build subtitle filter ---
VF_FILTER=""
if [ "$NO_SUBS" = false ]; then
  VF_FILTER="subtitles='${SRT_ESCAPED}':force_style='${SUB_STYLE}'"
fi

# --- 6. Determine audio strategy ---
HAS_BGM=false
HAS_NARRATION=false
NARRATION_COUNT=0

if [ "$NO_BGM" = false ] && [ -f "$BGM_FILE" ]; then
  HAS_BGM=true
  echo "BGM:        $BGM_FILE"
elif [ "$NO_BGM" = false ]; then
  echo "BGM:        (not found -- creating sine tone placeholder)"
  ffmpeg -f lavfi -i "sine=frequency=440:duration=${VIDEO_DURATION}" \
    -af "aformat=sample_rates=44100,volume=0.06" \
    -y "$BGM_FILE" 2>/dev/null
  HAS_BGM=true
fi

if [ "$BGM_ONLY" = false ] && [ -d "$NARRATION_DIR" ]; then
  NARRATION_COUNT=$(ls "$NARRATION_DIR"/narration-*.mp3 2>/dev/null | wc -l | tr -d ' ')
  if [ "$NARRATION_COUNT" -gt 0 ] && [ -f "$NARRATION_JSON" ]; then
    HAS_NARRATION=true
    echo "Narration:  $NARRATION_COUNT clips in $NARRATION_DIR/"
  fi
fi

# --- 7. Build and run ffmpeg ---
echo ""

if [ "$HAS_NARRATION" = true ] && [ "$HAS_BGM" = true ]; then
  # ===== TIER 3: Video + Subtitles + BGM + Narration =====
  echo "Mode: Full merge (video + subtitles + BGM + narration)"

  # Use Python to build the complex ffmpeg filter graph
  python3 - "$VIDEO" "$BGM_FILE" "$SRT_ESCAPED" "$SUB_STYLE" "$OUTPUT" \
    "$NARRATION_DIR" "$NARRATION_JSON" "$VF_FILTER" "$DRY_RUN" "$NO_SUBS" << 'PYEOF'
import json, sys, os, subprocess

video      = sys.argv[1]
bgm        = sys.argv[2]
srt_esc    = sys.argv[3]
sub_style  = sys.argv[4]
output     = sys.argv[5]
narr_dir   = sys.argv[6]
narr_json  = sys.argv[7]
vf_filter  = sys.argv[8]
dry_run    = sys.argv[9] == 'true'
no_subs    = sys.argv[10] == 'true'

narration = json.load(open(narr_json))

# Build inputs: 0=video, 1=bgm, 2..N=narration clips
inputs = [f'-i "{video}"', f'-i "{bgm}"']
filter_parts = []
narr_labels = []
n = 2  # input index

for i, entry in enumerate(narration):
    mp3 = os.path.join(narr_dir, f"narration-{i:03d}.mp3")
    if os.path.exists(mp3):
        inputs.append(f'-i "{mp3}"')
        delay_ms = entry["start"]
        filter_parts.append(f"[{n}]adelay={delay_ms}|{delay_ms},volume=1.0[n{i}]")
        narr_labels.append(f"[n{i}]")
        n += 1

if narr_labels:
    # Mix all narration clips
    filter_parts.append(
        "".join(narr_labels) +
        f"amix=inputs={len(narr_labels)}:normalize=0[narr_mixed]"
    )
    # BGM at low volume
    filter_parts.append("[1:a]volume=0.12,apad[bgm_low]")
    # Mix narration + BGM
    filter_parts.append("[narr_mixed][bgm_low]amix=inputs=2:normalize=0[final_audio]")
else:
    filter_parts.append("[1:a]volume=0.15,apad[final_audio]")

filter_str = ";\n".join(filter_parts)

vf_arg = f'-vf "{vf_filter}"' if not no_subs and vf_filter else ''

cmd = f"""ffmpeg {' '.join(inputs)} \\
  -filter_complex "{filter_str}" \\
  {vf_arg} \\
  -map 0:v -map "[final_audio]" \\
  -c:v libx264 -preset fast -crf 23 \\
  -c:a aac -b:a 128k \\
  -s 1280x720 \\
  -shortest -y "{output}"
"""

# Save the command for inspection
script_path = os.path.join(os.path.dirname(output), "ffmpeg-cmd.sh")
with open(script_path, "w") as f:
    f.write("#!/bin/bash\nset -e\n" + cmd + "\n")
os.chmod(script_path, 0o755)
print(f"FFmpeg script: {script_path}")

if dry_run:
    print("\n(dry run -- not executing)")
    print(cmd)
else:
    print("Rendering...")
    ret = os.system(f"bash '{script_path}'")
    if ret != 0:
        print(f"ERROR: ffmpeg exited with code {ret}")
        sys.exit(1)
PYEOF

elif [ "$HAS_BGM" = true ]; then
  # ===== TIER 2: Video + Subtitles + BGM =====
  echo "Mode: Video + subtitles + BGM"

  CMD=(ffmpeg -i "$VIDEO" -i "$BGM_FILE")

  if [ -n "$VF_FILTER" ]; then
    CMD+=(-vf "subtitles='${SRT_ESCAPED}':force_style='${SUB_STYLE}'")
  fi

  CMD+=(
    -filter_complex "[1:a]volume=0.15,apad[bgm_out]"
    -map 0:v -map "[bgm_out]"
    -c:v libx264 -preset fast -crf 23
    -c:a aac -b:a 128k
    -s 1280x720
    -shortest -y "$OUTPUT"
  )

  echo "Command: ${CMD[*]}"
  echo ""
  if [ "$DRY_RUN" = true ]; then
    echo "(dry run -- not executing)"
  else
    echo "Rendering..."
    "${CMD[@]}"
  fi

else
  # ===== TIER 1: Video + Subtitles only (no audio) =====
  echo "Mode: Video + subtitles (no audio)"

  CMD=(ffmpeg -i "$VIDEO")

  if [ -n "$VF_FILTER" ]; then
    CMD+=(-vf "subtitles='${SRT_ESCAPED}':force_style='${SUB_STYLE}'")
  fi

  CMD+=(
    -c:v libx264 -preset fast -crf 23
    -s 1280x720
    -an
    -y "$OUTPUT"
  )

  echo "Command: ${CMD[*]}"
  echo ""
  if [ "$DRY_RUN" = true ]; then
    echo "(dry run -- not executing)"
  else
    echo "Rendering..."
    "${CMD[@]}"
  fi
fi

# --- 8. Report ---
if [ "$DRY_RUN" = false ] && [ -f "$OUTPUT" ]; then
  echo ""
  echo "========================================"
  echo " Output"
  echo "========================================"
  ls -lh "$OUTPUT"
  DURATION=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$OUTPUT" 2>/dev/null || echo "?")
  echo "  Duration: ${DURATION}s"
  echo ""
  echo "Play:  open \"$OUTPUT\""
  echo "Upload: ready for distribution"
fi
